kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "1"
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:3
          ports:
            - containerPort: 9092
            - containerPort: 9097
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CFG_LISTENERS
              value: CLIENT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9097
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: CLIENT://kafka-service:9092,EXTERNAL://kafka-service:9097
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: CLIENT
            - name: KAFKA_CFG_MAX_PARTITION_FETCH_BYTES
              value: "10485760"
            - name: KAFKA_CFG_MAX_REQUEST_SIZE
              value: "10485760"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka-service
spec:
  type: NodePort
  ports:
    - name: kafka-port2
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 31092
    - name: kafka-port7
      protocol: TCP
      port: 9097
      targetPort: 9097
      nodePort: 31097
  selector:
    app: kafka
    id: "1"