apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ingress
  namespace: default
spec:
  defaultBackend:
    service:
      name: console
      port:
        number: 9443
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
             service:
                port:
                  number: 9443
                name: console
            path: /console
            pathType: Prefix
